export {default as Hero} from './hero/hero'
export {default as Slider} from './slider/slider'
export {default as WhyWe} from './why-we/why-we'
export {default as Menu} from './menu/menu'
export {default as Branches} from './branches/ourBranch'
